version: 2.1

orbs:
  node: circleci/node@4.7.0

workflows:
  build_test:
    jobs:
      - node/run:
        npm-run: build
        filters: 
            branches: 
              only: /^feat.*/

      - node/test:
        requires:
          - node/run
          filters: 
            branches: 
              only: /^feat.*/