version: 2.1

jobs:
  - build:       
      docker:
        - image: circleci/node:12
      steps:
        - checkout
        - run:
            name: Update NPM
            command: "sudo npm install -g npm@5"
        - restore_cache:
            key: 
            - dependency-cache-{{ checksum "package-lock.json" }}
            - v1-dependencies-
        - run:
            name: Install Dependencies
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
        - run:
            name: Run build
            command: npm run build
  - test:
      steps:
        - run:
          name: Run tests
          command: npm run test

workflows:
  build_test_deploy:
    jobs:
      - build:
        filters:  
            branche:
              only: /^feat.*/
      - test:
          requires:
            - build