version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build


workflows:
  build_test:
    jobs:
      - build
      - node/test:
        requires:
          - build
          filters: 
            branches: 
              only: /^feat.*/