version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
        name: Run build
        command: npm run build

  test:
    steps:
      - run: 
        name: Run tests
        command: npm run test


workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters: 
            branches: 
              only: /^feat.*/