version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
         
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          command: npm run build

  test:
    steps:
      - run: 
          
          command: npm run test


workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters: 
            branches: 
              only: /^feat.*/