version: 2.1

orbs:
  node: circleci/node@4.7
  aws-code-deploy: circleci/aws-code-deploy@0.0.11


workflows:
  test:
    jobs:
      - build:       
          version: '16.10'
          pkg-manager: npm  
          working_directory: ~/repo  
          steps:
            - checkout
          - run:
              name: Update NPM
              command: "sudo npm install -g npm@5"
          - restore_cache:
              key: dependency-cache-{{ checksum "package-lock.json" }}
          - run:
              name: Install Dependencies
              command: npm install
          - save_cache:
              key: dependency-cache-{{ checksum "package-lock.json" }}
              paths:
                - ./node_modules
          - run:
              name: Run build
              command: npm run build

      - test:
          version: '16.10'
          requires:
            - build
          pkg-manager: npm  
          working_directory: ~/repo  
          steps:
            - run:
              name: Run tests
              command: npm run test

        - deploy:
          requires: 
            - test


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
        requires:
          - build
      - deploy
        requires:
          - test
        filters:
          branches:
            only: master