version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Run build
          command: npm run build
  
  deploy:
    docker:
      - image: circleci/node:12
    
    steps:
      - checkout
      - run: echo "Hello World!"
     
workflows:
  build_deploy:
    jobs:
      - build:
          filters:
            branches: 
              only:
                - master
                - develop
                - /^feat.*/
      - deploy:
          requires:
            - build
          filters: 
            branches:
              only:
                - master